### ISSUE TITLE
user-can-join-waitlist

### ISSUE THREAD

**Issue by j-alejandro-araujo** [j-alejandro-araujo/LOTR-brawl#1]
## ⚙️ Feature

> ##### What capability will users have when this feature is merged?

User can….sign-up to join the waitlist.

## 🖼️ Wireframes

> ##### Wireframe screenshot(s) of what the app should look like when it is complete.

![Screenshot 2023-06-13 at 4 17 18 PM](https://github.com/j-alejandro-araujo/ajax-project/assets/91649194/aa80927f-9e52-4da6-bb96-e9a1f41601c1)
![Screenshot 2023-06-13 at 4 16 50 PM](https://github.com/j-alejandro-araujo/ajax-project/assets/91649194/78de8749-6612-4aba-b5fe-c63ce577c9a4)
![Screenshot 2023-06-13 at 4 18 44 PM](https://github.com/j-alejandro-araujo/ajax-project/assets/91649194/5261c749-b28e-461f-ab91-d39d94448b33)

## ✅ Task List

> ##### Commit checklist for tasks needed to complete the feature.

- [x] Create the HTML skeleton based on the provided prototype, start with mobile view.
- [x] Make sure that click targets are either `<a>` or `<button>` elements.
- [x] Start with the nav bar.
  - [x] Import font awesome 'bars' icon and place on the left side of the nav bar.
  - [x] Import main LOTR icon and center it in the nav bar.
  - [x] Add white line across the bottom of nav bar.
- [x] Import LOTR title image, center it, and place it under the nav bar.
- [x] Import img of Gandalf, on top of the Gandalf img.
  - [x] Add h2 with text "Do you dare pass?...".
  - [x] Add h3 with text "Join the waitlist".
  - [x] Create a button, with text "Sign-up". 
- [x] Create dropdown menu. for nav bar. 
  - [x] Add anchors to list. 
  - [x] Each anchor should move you to the clicked area on the page.
- [x] Create toggle function for navigation.
  - [x] It should expand the nav bar when page is stretched.
  - [x] It should collapse nav bar and show bars icon when page is shrinked.
- [x] Add h1 with text  "WHO WE ARE".
- [x] Create a text block w/ p element, where the info on "WHO WE ARE" will be stored. 
- [x] Add CSS styling to the page and make sure it matched the example.
- [x] Create a module.
  - [x] Add necessary HTML elements for the module.
  - [x] Add title "Sign-up". 
  - [x] Create two REQUIRED inputs for NAME and EMAIL ADDRESS. 
  - [x] Create two button to CONFIRM or CANCEL.
  - [x] Add transparent image. 
- [x] Add CSS styling to the module and make sure it matches the example.
- [x] Using JavaScript. add functionality to the module.
  - [x] When sign-up button is clicked, OPEN module. 
  - [x] When cancel button is clicked, CLOSE module. 
  - [x] When confirm button is clicked, "Thank you" text will appear and module will close.
  - [x] Use CSS to blur the background behind the module.
- [x] Remove all CSS styling that had no affect or was otherwise unnecessary.
- [x] Test all functionality again in a private browsing session.
- [x] Fix all errors.
