### ISSUE TITLE
user-can-view-characters

### ISSUE THREAD

**Issue by j-alejandro-araujo** [j-alejandro-araujo/LOTR-brawl#3]
## ⚙️ Feature

> ##### What capability will users have when this feature is merged?

User can view characters w/ bio info.

## 🖼️ Wireframes

> ##### Wireframe screenshot(s) of what the app should look like when it is complete.

<img width="902" alt="Screenshot 2023-06-18 at 12 29 23 PM" src="https://github.com/j-alejandro-araujo/LOTR-brawl/assets/91649194/db705e82-56c3-4dfa-9738-4f27c9b5d447">
<img width="331" alt="Screenshot 2023-06-18 at 12 29 44 PM" src="https://github.com/j-alejandro-araujo/LOTR-brawl/assets/91649194/b1494f23-2c49-4bac-93c2-e6825e132a75">

## ✅ Task List

> ##### Commit checklist for tasks needed to complete the feature.

- [x] Add HTML elements to create character carousel structure.
- [x] Add img and necessary content such as font awesome icons.
- [x] Adjust CSS to match the figma wireframes.
- [x] Make content adjustable for mobile and desktop using @screen CSS. 
- [x] Test page adjustable functionality.
- [x] Create img carousel.
  - [x] Add functionality to font awesome arrows. 
  - [x] Carousel should begin automatically and function on a timer. 
  - [x] User should be able to click back and forth between characters and the carousel should continue be active.
  - [x] Test carousel and make sure all bugs are fixed.
- [x] Connect carousel to LOTR API. 
  - [x] API should pull in bio text when a specific character is active in the carousel.
  - [x] Name and bio should change and match the active character. 
  - [x] Test functionality and fix any bugs. 
  - [x] Remove all CSS styling that had no affect or was otherwise unnecessary.
  - [x] Test all functionality again in a private browsing session.
  - [x] Fix all errors.
