### ISSUE TITLE
user-can-map

### ISSUE THREAD

**Issue by j-alejandro-araujo** [j-alejandro-araujo/LOTR-brawl#4]
## ⚙️ Feature

> ##### What capability will users have when this feature is merged?

User can view interactive map.

## 🖼️ Wireframes

> ##### Wireframe screenshot(s) of what the app should look like when it is complete.

![Screenshot 2023-06-22 at 9 09 36 AM](https://github.com/j-alejandro-araujo/LOTR-brawl/assets/91649194/7cbc0bb0-895d-49c1-bb7c-e64249798e53)
![Screenshot 2023-06-22 at 9 09 58 AM](https://github.com/j-alejandro-araujo/LOTR-brawl/assets/91649194/a75c8f59-7e87-41e9-886d-ab2832375348)
![Screenshot 2023-06-22 at 9 10 10 AM](https://github.com/j-alejandro-araujo/LOTR-brawl/assets/91649194/d48bf9d8-d8fb-4ed3-9f4f-a511ebe6678e)

## ✅ Task List

> ##### Commit checklist for tasks needed to complete the feature.

- [x] Add necessary HTML elements for the map, carousel, and info block.
- [x] Fill in the HTML elements w/ map img and location img. 
- [x] Add Chevron left and right FA icons.
- [x] Add CSS styling to match the figma prototype. 
- [x] Make sure the page is dynamic and adjusts per screen size mobile v desktop.
- [x] Use Leaflet to integrate map functionality.
  - [x] Add locations and pinpoints.
- [x] Create location carousel.
  - [x] Add functionality and to chevron left and right icons.
  - [x] Add location info to the block and integrate it w/ img location.
  - [x] Location info should change along w/ location img.
- [x] Name and bio should change and match the active character.
- [x] Test functionality and fix any bugs.
- [x] Remove all CSS styling that had no affect or was otherwise unnecessary.
- [x] Test all functionality again in a private browsing session.
- [x] Fix all errors.
